export default {
  DASHBOARD_PAGE: '/',
  DASHBOARD_STATE_PAGE: '/state-report',
  UNSAFE_PLACES_PAGE: '/unsafe-places',
  USEFUL_LINKS_PAGE: '/useful-links',
  ABOUT_US_PAGE: '/about-us',
  HELPLINE_LINK: 'HTTPS://WWW.MOHFW.GOV.IN/PDF/CORONVAVIRUSHELPLINENUMBER.PDF',
  GOVT_HEALTH_MINISTRY_LINK: 'HTTPS://WWW.MOHFW.GOV.IN/',
  WHO_LINK: 'HTTPS://WWW.WHO.INT/EMERGENCIES/DISEASES/NOVEL-CORONAVIRUS-2019',
  CDC_LINK: 'HTTPS://WWW.CDC.GOV/CORONAVIRUS/2019-NCOV/FAQ.HTML',
  CROWDSOURCE_LINK: 'HTTPS://BIT.LY/COVID19RESOURCELIST',
  WORLDWIDE_CASE_URL: 'https://www.worldometers.info/coronavirus/',
  LIVE_PATIENT_RECORDS: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSc_2y5N0I67wDU38DjDh35IZSIS30rQf7_NYZhtYYGU1jJYT6_kDx4YpF-qw0LSlGsBYP8pqM_a1Pd/pubhtml'
};
