module.exports = {
  REDIS_TIVO_ADDONS_SERVICES: 'REDIS_TIVO_ADDONS_SERVICES',
  REDIS_TIVO_CUSTOMER_INFO: 'REDIS_TIVO_CUSTOMER_INFO',
  REDIS_TIVO_PACKAGES: 'REDIS_TIVO_PACKAGES',
  REDIS_TIVO_REGIONS: 'REDIS_TIVO_REGIONS'
};
